/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.11).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import org.springframework.data.repository.CrudRepository;

import io.swagger.model.Projecte;

public interface ProjecteApi extends CrudRepository<Projecte, String> {
    @Override
    Projecte findOne(String id);
}
