/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.11).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import java.util.ArrayList;

import org.springframework.data.repository.CrudRepository;

import io.swagger.model.Tecnic;

public interface TecnicApi extends CrudRepository<Tecnic, String> {
    @Override
    Tecnic findOne(String idTecnic);

    ArrayList<Tecnic> findAllBynomCognom(String nom);

    ArrayList<Tecnic> findAllByestat(String estat);

}
